//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiPaladar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredient
    {
        public int Id { get; set; }
        public double Quantity { get; set; }
        public int IngredientProductId { get; set; }
        public int BaseProductId { get; set; }
        public int UnitMeasureId { get; set; }
    
        public virtual Product IngredientProduct { get; set; }
        public virtual Product BaseProduct { get; set; }
        public virtual UnitMeasure UnitMeasure { get; set; }
    }
}
