//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiPaladar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineItem
    {
        public int Id { get; set; }
        public double Quantity { get; set; }
        public int Product_Id { get; set; }
    
        public virtual UnitMeasure UnitMeasure { get; set; }
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
