//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiPaladar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Outgredients = new HashSet<Ingredient>();
            this.Ingredients = new HashSet<Ingredient>();
            this.Tags = new HashSet<Tag>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal SalePrice { get; set; }
        public int UMFamilyId { get; set; }
        public string ImageFileName { get; set; }
        public decimal CostPrice { get; set; }
        public int CostUMId { get; set; }
        public int Code { get; set; }
        public decimal ArbitraryCost { get; set; }
        public ProductType ProductType { get; set; }
        public double RecipeQuantity { get; set; }
        public double EdiblePart { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string ProductionProcess { get; set; }
        public string Description { get; set; }
        public int RecipeUnitMeasure_Id { get; set; }
        public bool DoneByUser { get; set; }
        public string PrintString { get; set; }
    
        public virtual ICollection<Ingredient> Outgredients { get; set; }
        public virtual ICollection<Ingredient> Ingredients { get; set; }
        public virtual UMFamily UMFamily { get; set; }
        public virtual UnitMeasure CostUnitMeasure { get; set; }
        public virtual ICollection<Tag> Tags { get; set; }
        public virtual Category Category { get; set; }
        public virtual UnitMeasure RecipeUnitMeasure { get; set; }
    }
}
