//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiPaladar.Entities
{
    using System;
    
    public enum ProductType : int
    {
        FinishedGoods = 0,
        WorkInProcess = 1,
        RawMaterials = 2,
        CompraVenta = 3
    }
}
