//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiPaladar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale : Order
    {
        public Sale()
        {
            this.SaleLineItems = new HashSet<SaleLineItem>();
        }
    
        public Nullable<System.DateTime> DateClosed { get; set; }
        public Nullable<System.DateTime> DatePrinted { get; set; }
        public decimal Discount { get; set; }
        public bool DiscountInPercent { get; set; }
        public decimal Cash { get; set; }
        public int Prints { get; set; }
        public int Persons { get; set; }
        public bool Paid { get; set; }
        public Nullable<int> Number { get; set; }
        public decimal SubTotal { get; set; }
        public decimal Total { get; set; }
        public bool Closed { get; set; }
        public decimal Tax { get; set; }
        public bool TaxInPercent { get; set; }
        public decimal Tips { get; set; }
        public decimal TotalCost { get; set; }
        public Nullable<int> ShiftId { get; set; }
        public int Voids { get; set; }
        public int VoidsAfterReceipt { get; set; }
    
        public virtual Shift Shift { get; set; }
        public virtual ICollection<SaleLineItem> SaleLineItems { get; set; }
    }
}
