//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiPaladar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleLineItem : LineItem
    {
        public decimal Amount { get; set; }
        public bool Printed { get; set; }
        public decimal Cost { get; set; }
    
        public virtual Sale Sale { get; set; }
    }
}
